print('----------------------------------------------')
print('------Exercícios de Operações Matemática------')
print('----------------------------------------------')

# teste de operação clássico
print(f'Digite dois números, para fazer as Operações Matemática.')
n1 = float(input('Digite o primeiro número inteiro: '))
n2 = float(input('Digite o segundo número inteiro: '))
soma = n1+n2
print(f'Soma = {n1+n2}')
print(f'Subtração = {n1-n2}')
print(f'Multiplicação = {n1*n2}')
print(f'Divisão = {n1/n2}')
print()
print(f'Soma = {n1+n2}; Subtração = {n1-n2}; Multiplicação = {n1*n2}; Divisão = {n1/n2}')
print()
print()
# teste de operadores diferentes v2
print(f'Digite dois números, para fazer as Operações Matemática.(Versão 2)')
n1 = float(input('Digite o Primeiro número inteiro: '))
n2 = float(input('Digite o Segundo número inteiro: '))
print(f'Potência = {n1**n2}')
print(f'Divisão Inteira = {n1//n2}')
print(f'Resto = {n1%n2}')
print()
print(f'Potência = {n1**n2}; Divisão Inteira = {n1//n2}; Resto da Divisão = {n1%n2}')
print()
print('FIM do Programa.')
print()